# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170129_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='myLocation', max_length=200),
        ),
    ]
